name: 'Runner'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: write


jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

  - name: Modifiy the specific files using scripts
    run: |
      go run main.go -dir 1

      git config --global user.name "Bot"
      git config --global user.email "kandemir@gmail.com"

      git add -A
      git commit -m "Update map"
      git push
