name: Game Input

on:
  issues:
    types:
      - opened
      
concurrency: single
      
permissions:
  contents: write
  issues: write
    
jobs:
  go-right:
    if: github.event.issue.title == 'go right'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go run main.go -dir 1
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "go right"
          git push
      - uses: peter-evans/close-issue@v2

  go-down:
    if: github.event.issue.title == 'go down'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go run main.go -dir 2
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "go down"
          git push
      - uses: peter-evans/close-issue@v2

  go-left:
    if: github.event.issue.title == 'go left'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go run main.go -dir 3
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "go left"
          git push
      - uses: peter-evans/close-issue@v2

  go-up:
    if: github.event.issue.title == 'go up'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go run main.go -dir 4
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "go up"
          git push
      - uses: peter-evans/close-issue@v2
