name: Game Input

on:
  issues:
    types:
      - opened

permissions:
  contents: write
  issues: write

jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}

    steps:
    - id: runner
      run: |
        if [ "${{ github.actor }}" == "bahadir" ]; then
          echo "::set-output name=runner::self-hosted"    
        else
          echo "::set-output name=runner::ubuntu-latest"
        fi
        
  follow-command:
    needs: [choose-runner]
    if: contains(github.event.issue.labels.*.name, 'game-input')

    runs-on: ${{ needs.choose-runner.outputs.runner }}

    steps:
      - name: Get repository stats
        run: echo "GAME_XP=$(curl -s https://api.github.com/repos/bahadir/bahadir | jq .stargazers_count)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Follow user command
        env:
          GAME_INPUT: ${{ github.event.issue.title }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git pull
          rm data/map-*.png
          go run main.go
          git add -A
          git commit -m "Follow user command"  
          git push
      - uses: peter-evans/close-issue@v2
